let data = [
    { 
        name: "Ribbed Cotton Bodysuits",
        slug: "Ribbed Cotton Bodysuits",
        img: "/assets/images/Image-1-1.jpg",
        price: "80",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "5",
        numberOfRating: "84",
        stoke: "23",
        category: "fashion",
        brand: "Aarong",
        coupon: 'Aarong01',
        discount: 25,
        discountLimit: 0,
        totalSell: 320
    },    
    {
        name: "Twill Shirt for Woman",
        slug: "Twill Shirt for Woman",
        img: "/assets/images/Image-2-1.jpg",
        price: "110",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.4",
        numberOfRating: "84",
        stoke: "42",
        category: "fashion",
        brand: "Ecstasy",
        coupon: 'Ecstasy05',
        discount: 10,
        discountLimit: 0,
        totalSell: 142
    },
    {
        name: "Grand Atlantic Boots",
        slug: "Grand Atlantic Boots",
        img: "/assets/images/Image-3-1.jpg",
        price: "210",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "5",
        numberOfRating: "149",
        stoke: "0",
        category: "fashion",
        brand: "Apex",
        coupon: 'Apex00',
        discount: 40,
        discountLimit: 0,
        totalSell: 231
    },
    {
        name: "Women's Faux Shirt",
        slug: "Women's Faux Shirt",
        img: "/assets/images/Image-4-1.jpg",
        price: "150",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "5",
        numberOfRating: "84",
        stoke: "100",
        category: "fashion",
        brand: "Yellow",
        coupon: 'Yellow12',
        discount: 30,
        discountLimit: 0,
        totalSell: 154
    },
    {
        name: "Double-breasted Blazer",
        slug: "Double-breasted Blazer",
        img: "/assets/images/Image-5-1.jpg",
        price: "115",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.5",
        numberOfRating: "44",
        stoke: "41",
        category: "fashion",
        brand: "Yellow",
        coupon: 'Yellow12',
        discount: 30,
        discountLimit: 0,
        totalSell: 140
    },
    {
        name: "Wedding Diamond Ring",
        slug: "Wedding Diamond Ring",
        img: "/assets/images/Image-6-1.jpg",
        price: "115",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.9",
        numberOfRating: "94",
        stoke: "87",
        category: "fashion",
        brand: "Aarong",
        coupon: 'Aarong07',
        discount: 20,
        discountLimit: 0,
        totalSell: 214
    },
    {
        name: "Denim Official Coat",
        slug: "Denim Official Coat",
        img: "/assets/images/Image-7-1.jpg",
        price: "220",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.3",
        numberOfRating: "124",
        stoke: "121",
        category: "fashion",
        brand: "Aarong",
        coupon: 'Aarong07',
        discount: 50,
        discountLimit: 0,
        totalSell: 310
    },
    {
        name: "Dress for Girl",
        slug: "Dress for Girl",
        img: "/assets/images/Image-8-1.jpg",
        price: "80",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.8",
        numberOfRating: "412",
        stoke: "48",
        category: "fashion",
        brand: "Twelve",
        coupon: 'Twelve00',
        discount: 30,
        discountLimit: 0,
        totalSell: 511
    }
]

export default data