let data = [
    {
        name: "Ribbed Cotton Bodysuits",
        slug: "product-1",
        img: "/assets/images/Image-1-1.jpg",
        price: "80",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "5",
        numberOfRating: "84",
        stoke: "23",
        category: "fashion",
        brand: "Aarong",
        coupon: 'Aarong01',
        discount: 25,
        discountLimit: 0,
        totalSell: 320
    },    
    {
        name: "Twill Shirt for Woman",
        slug: "product-2",
        img: "/assets/images/Image-2-1.jpg",
        price: "110",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.4",
        numberOfRating: "84",
        stoke: "42",
        category: "fashion",
        brand: "Ecstasy",
        coupon: 'Ecstasy05',
        discount: 10,
        discountLimit: 0,
        totalSell: 142
    },
    {
        name: "Grand Atlantic Boots",
        slug: "product-3",
        img: "/assets/images/Image-3-1.jpg",
        price: "210",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "5",
        numberOfRating: "149",
        stoke: "124",
        category: "fashion",
        brand: "Apex",
        coupon: 'Apex00',
        discount: 40,
        discountLimit: 0,
        totalSell: 231
    },
    {
        name: "Women's Faux Shirt",
        slug: "product-4",
        img: "/assets/images/Image-4-1.jpg",
        price: "150",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "5",
        numberOfRating: "84",
        stoke: "100",
        category: "fashion",
        brand: "Yellow",
        coupon: 'Yellow12',
        discount: 30,
        discountLimit: 0,
        totalSell: 154
    },
    {
        name: "Double-breasted Blazer",
        slug: "product-5",
        img: "/assets/images/Image-5-1.jpg",
        price: "115",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.5",
        numberOfRating: "44",
        stoke: "41",
        category: "fashion",
        brand: "Yellow",
        coupon: 'Yellow12',
        discount: 30,
        discountLimit: 0,
        totalSell: 140
    },
    {
        name: "Wedding Diamond Ring",
        slug: "product-6",
        img: "/assets/images/Image-6-1.jpg",
        price: "115",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.9",
        numberOfRating: "94",
        stoke: "87",
        category: "fashion",
        brand: "Aarong",
        coupon: 'Aarong07',
        discount: 20,
        discountLimit: 0,
        totalSell: 214
    },
    {
        name: "Denim Official Coat",
        slug: "product-7",
        img: "/assets/images/Image-7-1.jpg",
        price: "220",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.3",
        numberOfRating: "124",
        stoke: "121",
        category: "fashion",
        brand: "Aarong",
        coupon: 'Aarong07',
        discount: 50,
        discountLimit: 0,
        totalSell: 310
    },
    {
        name: "Dress for Girl",
        slug: "product-8",
        img: "/assets/images/Image-8-1.jpg",
        price: "80",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.8",
        numberOfRating: "412",
        stoke: "48",
        category: "fashion",
        brand: "Twelve",
        coupon: 'Twelve00',
        discount: 30,
        discountLimit: 0,
        totalSell: 511
    },
    {
        name: "Shirt for Woman",
        slug: "product-9",
        img: "/assets/images/Image-9-1.jpg",
        price: "80",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.6",
        numberOfRating: "210",
        stoke: "113",
        category: "fashion",
        brand: "Easy",
        coupon: 'Easy30',
        discount: 30,
        discountLimit: 0,
        totalSell: 415
    },
    {
        name: "Skinny Cotton Pant",
        slug: "product-10",
        img: "/assets/images/Image-10-1.jpg",
        price: "125",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.2",
        numberOfRating: "127",
        stoke: "173",
        category: "fashion",
        brand: "Easy",
        coupon: 'Easy40',
        discount: 40,
        discountLimit: 0,
        totalSell: 317
    },
    {
        name: "Tinted Sunglasses",
        slug: "product-11",
        img: "/assets/images/Image-11-1.jpg",
        price: "200",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.9",
        numberOfRating: "145",
        stoke: "59",
        category: "fashion",
        brand: "Aarong",
        coupon: 'Aarong50',
        discount: 50,
        discountLimit: 0,
        totalSell: 302
    },
    {
        name: "Men's Classic Stretch",
        slug: "product-12",
        img: "/assets/images/Image-12-1.jpg",
        price: "180",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "5",
        numberOfRating: "87",
        stoke: "89",
        category: "fashion",
        brand: "Richman",
        coupon: 'Richman01',
        discount: 40,
        discountLimit: 0,
        totalSell: 157
    },    
    {
        name: "Girls Metallic Coat",
        slug: "product-13",
        img: "/assets/images/Image-13-1.jpg",
        price: "170",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.6",
        numberOfRating: "151",
        stoke: "12",
        category: "fashion",
        brand: "Twelve",
        coupon: 'Twelve20',
        discount: 20,
        discountLimit: 0,
        totalSell: 214
    },
    {
        name: "Varsi Leather Bag",
        slug: "product-14",
        img: "/assets/images/Image-14-1.jpg",
        price: "115",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "5",
        numberOfRating: "82",
        stoke: "52",
        category: "fashion",
        brand: "Aarong",
        coupon: 'Aarong50',
        discount: 50,
        discountLimit: 0,
        totalSell: 215
    },
    {
        name: "Men's Classic Polo",
        slug: "product-15",
        img: "assets/images/Image-15-1.jpg",
        price: "180",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.5",
        numberOfRating: "174",
        stoke: "72",
        category: "fashion",
        brand: "Polo",
        coupon: 'Polo10',
        discount: 10,
        discountLimit: 0,
        totalSell: 256
    },
    {
        name: "Touch Interlock Polo",
        slug: "product-16",
        img: "/assets/images/Image-16-1.jpg",
        price: "140",
        description: "Matent maecenas nec massa viverra aci ute litora aliquam habitant proin commodo bibendum rutru habitant est magnis quisque aliquet congue vesti bulum suscipi erose tellus odio elite purus feugiat prim libero senes nisie gravia",
        carddescription: "Matent maecenas nec massa viverra aci ute litora",
        rating: "4.7",
        numberOfRating: "177",
        stoke: "78",
        category: "fashion",
        brand: "Polo",
        coupon: 'Polo20',
        discount: 20,
        discountLimit: 0,
        totalSell: 311
    },
]

export default data